### PR TITLE
Lighthouse funcs titile

### PR DESCRIPTION
**Pull request by newgooood**
### Add a heading text
**Add a bold text**
_Add a italic text_

> Add a quote
`add a code`
_nothing..._
`add a code line1
code line2

code line4`

[add a link](niuguodong.com)

- bulleted list line1
- bulleted list line2

1. numbered list line1
2. numbered list line2

- [ ] task list line1
- [ ] task list line2

@newguodong 

#reference an issue, pull request, or discussion

/slash commands

`add code`
`add code`

```c
int main(void)
{
    ??
}
```

### CODE REVIEW

**Comment by newgooood** [comment]
haha edit again

**Comment by newgooood** [comment]
> ### Add a heading text
> 
> **Add a bold text** _Add a italic text_
> 
> > Add a quote
> > `add a code`
> > _nothing..._
> > `add a code line1
> > code line2
> 
> code line4`
> 
> [add a link](niuguodong.com)
> 
>     * bulleted list line1
> 
>     * bulleted list line2
> 
> 
>     1. numbered list line1
> 
>     2. numbered list line2
> 
> 
>     * [ ]  task list line1
> 
>     * [ ]  task list line2
> 
> 
> @newguodong
> 
> #reference an issue, pull request, or discussion
> 
> /slash commands
> 
> `add code` `add code`
> 
> ```c
> int main(void)
> {
>     ??
> }
> ```

test quote reply

**Review by newguodong — CHANGES_REQUESTED** [review]
Please modify lighthouse.py to get better

**Comment by newgooood** [comment]
> Please modify lighthouse.py to get better

got it

**Comment by newgooood** [comment]
> Please modify lighthouse.py to get better

I've finished your suggestions, please review again!

@newguodong

**Review by newguodong — APPROVED** [review]
good, I like this

**Pull request merged**
